[tool.poetry]
name = "rooms"
version = "0.1.0"
description = ""
authors = ["Stereopix"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
